version: '2'
services:
    web:
        build: .
        stdin_open: true
        tty: true
        ports:
            - "8881:8881"
        depends_on:
            - mongo
    mongo:
        image: mongo:3.4.0
        ports:
            - "27017:27017"
